---
development:
  cloud_name: tracykaur
  api_key: '819765554245179'
  api_secret: MYhUTxctAxIrisZo20iiTuQiXEE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: tracykaur
  api_key: '819765554245179'
  api_secret: MYhUTxctAxIrisZo20iiTuQiXEE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: tracykaur
  api_key: '819765554245179'
  api_secret: MYhUTxctAxIrisZo20iiTuQiXEE
  enhance_image_tag: true
  static_image_support: false
